programConfig = DBSCAN,KMeans_Clustering,Hierarchical_Clustering2,MCL_norm,cluster_dp
dataConfig = fraenti_s3
qualityMeasures = SilhouetteValueRClusteringQualityMeasure,TransClustFClusteringQualityMeasure,TransClustF2ClusteringQualityMeasure,FDRClusteringQualityMeasure,FPRClusteringQualityMeasure,RandIndexClusteringQualityMeasure,SensitivityClusteringQualityMeasure,SpecificityClusteringQualityMeasure,DaviesBouldinIndexRClusteringQualityMeasure,DunnIndexRClusteringQualityMeasure,FowlkesMallowsIndexRClusteringQualityMeasure,JaccardIndexRClusteringQualityMeasure,RandIndexRClusteringQualityMeasure,VMeasureClusteringQualityMeasure
mode = parameter_optimization
optimizationMethod = DivisiveParameterOptimizationMethod
optimizationCriterion = TransClustFClusteringQualityMeasure
optimizationIterations = 1000

[DBSCAN]
optimizationParameters = eps,MinPts

[clusterONE]
optimizationParameters = s,d

[cluster_dp]
optimizationParameters = dc,k

[TransClust_2]
optimizationParameters = T

[MCL_norm]
optimizationParameters = I

[APcluster_1]
optimizationParameters = preference,maxits,convits,dampfact

[KMeans_Clustering]
optimizationParameters = k

[KMedoids_Clustering]
optimizationParameters = k

[Hierarchical_Clustering2]
optimizationParameters = k,method

[Spectral_Clustering]
optimizationParameters = k

[SOM]
optimizationParameters = x,y

[Fanny_Clustering]
optimizationParameters = k,membexp

