programConfig = DBSCAN,KMedoids_Clustering,KMeans_Clustering,TransClust_2,SOM,Spectral_Clustering,cluster_dp,Fanny_Clustering_3membexp,Hierarchical_Clustering2,APcluster_1,MCL_norm,clusterONE
dataConfig = chang_spiral,fu_flame,astral_40,astral_40_seq_blast_100,ppi_mips,chang_pathbased,chang_spiral,veenman_r15,zahn_compound,gionis_aggregation
qualityMeasures = SilhouetteValueRClusteringQualityMeasure,TransClustFClusteringQualityMeasure,TransClustF2ClusteringQualityMeasure,FDRClusteringQualityMeasure,FPRClusteringQualityMeasure,RandIndexClusteringQualityMeasure,SensitivityClusteringQualityMeasure,SpecificityClusteringQualityMeasure,DaviesBouldinIndexRClusteringQualityMeasure,DunnIndexRClusteringQualityMeasure,FowlkesMallowsIndexRClusteringQualityMeasure,JaccardIndexRClusteringQualityMeasure,RandIndexRClusteringQualityMeasure,VMeasureClusteringQualityMeasure
mode = parameter_optimization
optimizationMethod = DivisiveParameterOptimizationMethod
optimizationCriterion = TransClustFClusteringQualityMeasure
optimizationIterations = 1000

[DBSCAN]
optimizationParameters = eps,MinPts

[clusterONE]
optimizationParameters = s,d

[cluster_dp]
optimizationParameters = dc,k

[TransClust_2]
optimizationParameters = T

[MCL_norm]
optimizationParameters = I

[APcluster_1]
optimizationParameters = preference,maxits,convits,dampfact

[KMeans_Clustering]
optimizationParameters = k

[KMedoids_Clustering]
optimizationParameters = k

[Hierarchical_Clustering2]
optimizationParameters = k,method

[Spectral_Clustering]
optimizationParameters = k

[SOM]
optimizationParameters = x,y

[Fanny_Clustering_3membexp]
optimizationParameters = k,membexp

