programConfig = DBSCAN,Fanny_Clustering_3membexp,KMedoids_Clustering,KMeans_Clustering,TransClust_2,Hierarchical_Clustering2,APcluster_1,MCL_norm,SOM,Spectral_Clustering,cluster_dp,clusterONE_norm,MCODE
dataConfig = boneMarrowGeneExpr
qualityMeasures = SilhouetteValueRClusteringQualityMeasure,TransClustFClusteringQualityMeasure,TransClustF2ClusteringQualityMeasure,FDRClusteringQualityMeasure,FPRClusteringQualityMeasure,RandIndexClusteringQualityMeasure,SensitivityClusteringQualityMeasure,SpecificityClusteringQualityMeasure,DaviesBouldinIndexRClusteringQualityMeasure,DunnIndexRClusteringQualityMeasure,FowlkesMallowsIndexRClusteringQualityMeasure,JaccardIndexRClusteringQualityMeasure,RandIndexRClusteringQualityMeasure,VMeasureClusteringQualityMeasure
mode = parameter_optimization
optimizationMethod = DivisiveParameterOptimizationMethod
optimizationCriterion = TransClustFClusteringQualityMeasure
optimizationIterations = 1000

[DBSCAN]
optimizationParameters = eps,MinPts

[clusterONE_norm]
optimizationParameters = s,d

[cluster_dp]
optimizationParameters = dc,k

[TransClust_2]
optimizationParameters = T

[MCL_norm]
optimizationParameters = I

[APcluster_1]
optimizationParameters = preference,maxits,convits,dampfact

[KMeans_Clustering]
optimizationParameters = k

[KMedoids_Clustering]
optimizationParameters = k

[Hierarchical_Clustering2]
optimizationParameters = k,method

[Spectral_Clustering]
optimizationParameters = k

[SOM]
optimizationParameters = x,y

[Fanny_Clustering_3membexp]
optimizationParameters = k,membexp

[MCODE]
optimizationParameters = cutoff,haircut,fluff,v
maxExecutionTimeMinutes = 10
