programConfig = clusterONE_norm,MCODE,DBSCAN,Fanny_Clustering_3membexp,KMedoids_Clustering,KMeans_Clustering,TransClust_2,Hierarchical_Clustering2,APcluster_1,MCL_norm,SOM,Spectral_Clustering,cluster_dp,clusterONE
dataConfig = chang_pathbased,gionis_aggregation,synthetic_cassini250
qualityMeasures = SilhouetteValueRClusteringQualityMeasure,TransClustFClusteringQualityMeasure,TransClustF2ClusteringQualityMeasure,FDRClusteringQualityMeasure,FPRClusteringQualityMeasure,RandIndexClusteringQualityMeasure,SensitivityClusteringQualityMeasure,SpecificityClusteringQualityMeasure,DaviesBouldinIndexRClusteringQualityMeasure,DunnIndexRClusteringQualityMeasure,FowlkesMallowsIndexRClusteringQualityMeasure,JaccardIndexRClusteringQualityMeasure,RandIndexRClusteringQualityMeasure,VMeasureClusteringQualityMeasure
mode = robustnessAnalysis
uniqueRunIdentifiers = 05_22_2015-14_41_27_clusterONE_1,05_22_2015-14_43_34_clusterONE_2,05_22_2015-14_43_36_clusterONE_3,05_22_2015-23_55_53_clusterONE_4,05_14_2015-14_37_07_mcode_vs_all,05_14_2015-20_39_29_mcode_vs_all_2,05_19_2015-16_06_06_mcode_vs_all_3,05_21_2015-13_47_30_mcode_vs_all_4_revcutoff,05_12_2015-10_10_25_all_except_mcode_vs_all_except_fraenti_1,05_13_2015-09_31_59_all_except_mcode_vs_all_except_fraenti_2
randomizer = RemoveAndAddNoiseDataRandomizer
numberOfRandomizedDataSets = 10

[MCODE]
maxExecutionTimeMinutes = 20

[RemoveAndAddNoiseDataRandomizer_1]
add = 0.0
remove = 0.2

[RemoveAndAddNoiseDataRandomizer_2]
add = 0.0
remove = 0.4

[RemoveAndAddNoiseDataRandomizer_3]
add = 0.2
remove = 0.0

[RemoveAndAddNoiseDataRandomizer_4]
add = 0.2
remove = 0.2

[RemoveAndAddNoiseDataRandomizer_5]
add = 0.2
remove = 0.4

[RemoveAndAddNoiseDataRandomizer_6]
add = 0.4
remove = 0.0

[RemoveAndAddNoiseDataRandomizer_7]
add = 0.4
remove = 0.2

[RemoveAndAddNoiseDataRandomizer_8]
add = 0.4
remove = 0.4

